//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.12

pub use super::account::Entity as Account;
pub use super::set::Entity as Set;
pub use super::up::Entity as Up;
pub use super::video::Entity as Video;
pub use super::video_set::Entity as VideoSet;
pub use super::video_up::Entity as VideoUp;
