//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.12

use sea_orm::entity::prelude::*;

#[derive(Copy, Clone, Default, Debug, DeriveEntity)]
pub struct Entity;

impl EntityName for Entity {
    fn table_name(&self) -> &str {
        "set"
    }
}

#[derive(Clone, Debug, PartialEq, DeriveModel, DeriveActiveModel, Eq)]
pub struct Model {
    pub set_id: i64,
    pub name: String,
    pub state: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveColumn)]
pub enum Column {
    SetId,
    Name,
    State,
}

#[derive(Copy, Clone, Debug, EnumIter, DerivePrimaryKey)]
pub enum PrimaryKey {
    SetId,
}

impl PrimaryKeyTrait for PrimaryKey {
    type ValueType = i64;
    fn auto_increment() -> bool {
        false
    }
}

#[derive(Copy, Clone, Debug, EnumIter)]
pub enum Relation {
    SetAccount,
    VideoSet,
}

impl ColumnTrait for Column {
    type EntityName = Entity;
    fn def(&self) -> ColumnDef {
        match self {
            Self::SetId => ColumnType::BigInteger.def(),
            Self::Name => ColumnType::String(StringLen::None).def(),
            Self::State => ColumnType::custom("enum_text").def(),
        }
    }
}

impl RelationTrait for Relation {
    fn def(&self) -> RelationDef {
        match self {
            Self::SetAccount => Entity::has_many(super::set_account::Entity).into(),
            Self::VideoSet => Entity::has_many(super::video_set::Entity).into(),
        }
    }
}

impl Related<super::set_account::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::SetAccount.def()
    }
}

impl Related<super::video_set::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::VideoSet.def()
    }
}

impl Related<super::account::Entity> for Entity {
    fn to() -> RelationDef {
        super::set_account::Relation::Account.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::set_account::Relation::Set.def().rev())
    }
}

impl Related<super::video::Entity> for Entity {
    fn to() -> RelationDef {
        super::video_set::Relation::Video.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::video_set::Relation::Set.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
