//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.12

use sea_orm::entity::prelude::*;

#[derive(Copy, Clone, Default, Debug, DeriveEntity)]
pub struct Entity;

impl EntityName for Entity {
    fn table_name(&self) -> &str {
        "up"
    }
}

#[derive(Clone, Debug, PartialEq, DeriveModel, DeriveActiveModel, Eq)]
pub struct Model {
    pub up_id: i64,
    pub name: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveColumn)]
pub enum Column {
    UpId,
    Name,
}

#[derive(Copy, Clone, Debug, EnumIter, DerivePrimaryKey)]
pub enum PrimaryKey {
    UpId,
}

impl PrimaryKeyTrait for PrimaryKey {
    type ValueType = i64;
    fn auto_increment() -> bool {
        false
    }
}

#[derive(Copy, Clone, Debug, EnumIter)]
pub enum Relation {
    VideoUp,
}

impl ColumnTrait for Column {
    type EntityName = Entity;
    fn def(&self) -> ColumnDef {
        match self {
            Self::UpId => ColumnType::BigInteger.def(),
            Self::Name => ColumnType::String(StringLen::None).def(),
        }
    }
}

impl RelationTrait for Relation {
    fn def(&self) -> RelationDef {
        match self {
            Self::VideoUp => Entity::has_many(super::video_up::Entity).into(),
        }
    }
}

impl Related<super::video_up::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::VideoUp.def()
    }
}

impl Related<super::video::Entity> for Entity {
    fn to() -> RelationDef {
        super::video_up::Relation::Video.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::video_up::Relation::Up.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
