//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.12

use sea_orm::entity::prelude::*;

#[derive(Copy, Clone, Default, Debug, DeriveEntity)]
pub struct Entity;

impl EntityName for Entity {
    fn table_name(&self) -> &str {
        "video_up"
    }
}

#[derive(Clone, Debug, PartialEq, DeriveModel, DeriveActiveModel, Eq)]
pub struct Model {
    pub bv_id: String,
    pub up_id: i64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveColumn)]
pub enum Column {
    BvId,
    UpId,
}

#[derive(Copy, Clone, Debug, EnumIter, DerivePrimaryKey)]
pub enum PrimaryKey {
    BvId,
    UpId,
}

impl PrimaryKeyTrait for PrimaryKey {
    type ValueType = (String, i64);
    fn auto_increment() -> bool {
        false
    }
}

#[derive(Copy, Clone, Debug, EnumIter)]
pub enum Relation {
    Up,
    Video,
}

impl ColumnTrait for Column {
    type EntityName = Entity;
    fn def(&self) -> ColumnDef {
        match self {
            Self::BvId => ColumnType::String(StringLen::None).def(),
            Self::UpId => ColumnType::BigInteger.def(),
        }
    }
}

impl RelationTrait for Relation {
    fn def(&self) -> RelationDef {
        match self {
            Self::Up => Entity::belongs_to(super::up::Entity)
                .from(Column::UpId)
                .to(super::up::Column::UpId)
                .into(),
            Self::Video => Entity::belongs_to(super::video::Entity)
                .from(Column::BvId)
                .to(super::video::Column::BvId)
                .into(),
        }
    }
}

impl Related<super::up::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Up.def()
    }
}

impl Related<super::video::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Video.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
