//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.12

use sea_orm::entity::prelude::*;

#[derive(Copy, Clone, Default, Debug, DeriveEntity)]
pub struct Entity;

impl EntityName for Entity {
    fn table_name(&self) -> &str {
        "video"
    }
}

#[derive(Clone, Debug, PartialEq, DeriveModel, DeriveActiveModel, Eq)]
pub struct Model {
    pub bv_id: String,
    pub title: String,
    pub state: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveColumn)]
pub enum Column {
    BvId,
    Title,
    State,
}

#[derive(Copy, Clone, Debug, EnumIter, DerivePrimaryKey)]
pub enum PrimaryKey {
    BvId,
}

impl PrimaryKeyTrait for PrimaryKey {
    type ValueType = String;
    fn auto_increment() -> bool {
        false
    }
}

#[derive(Copy, Clone, Debug, EnumIter)]
pub enum Relation {
    VideoSet,
    VideoUp,
}

impl ColumnTrait for Column {
    type EntityName = Entity;
    fn def(&self) -> ColumnDef {
        match self {
            Self::BvId => ColumnType::String(StringLen::None).def(),
            Self::Title => ColumnType::String(StringLen::None).def(),
            Self::State => ColumnType::custom("enum_text").def(),
        }
    }
}

impl RelationTrait for Relation {
    fn def(&self) -> RelationDef {
        match self {
            Self::VideoSet => Entity::has_many(super::video_set::Entity).into(),
            Self::VideoUp => Entity::has_many(super::video_up::Entity).into(),
        }
    }
}

impl Related<super::video_set::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::VideoSet.def()
    }
}

impl Related<super::video_up::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::VideoUp.def()
    }
}

impl Related<super::set::Entity> for Entity {
    fn to() -> RelationDef {
        super::video_set::Relation::Set.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::video_set::Relation::Video.def().rev())
    }
}

impl Related<super::up::Entity> for Entity {
    fn to() -> RelationDef {
        super::video_up::Relation::Up.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::video_up::Relation::Video.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
