//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.12

use sea_orm::entity::prelude::*;

#[derive(Copy, Clone, Default, Debug, DeriveEntity)]
pub struct Entity;

impl EntityName for Entity {
    fn table_name(&self) -> &str {
        "video_set"
    }
}

#[derive(Clone, Debug, PartialEq, DeriveModel, DeriveActiveModel, Eq)]
pub struct Model {
    pub bv_id: String,
    pub set_id: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveColumn)]
pub enum Column {
    BvId,
    SetId,
}

#[derive(Copy, Clone, Debug, EnumIter, DerivePrimaryKey)]
pub enum PrimaryKey {
    BvId,
    SetId,
}

impl PrimaryKeyTrait for PrimaryKey {
    type ValueType = (String, i32);
    fn auto_increment() -> bool {
        false
    }
}

#[derive(Copy, Clone, Debug, EnumIter)]
pub enum Relation {
    Set,
    Video,
}

impl ColumnTrait for Column {
    type EntityName = Entity;
    fn def(&self) -> ColumnDef {
        match self {
            Self::BvId => ColumnType::String(StringLen::None).def(),
            Self::SetId => ColumnType::Integer.def(),
        }
    }
}

impl RelationTrait for Relation {
    fn def(&self) -> RelationDef {
        match self {
            Self::Set => Entity::belongs_to(super::set::Entity)
                .from(Column::SetId)
                .to(super::set::Column::SetId)
                .into(),
            Self::Video => Entity::belongs_to(super::video::Entity)
                .from(Column::BvId)
                .to(super::video::Column::BvId)
                .into(),
        }
    }
}

impl Related<super::set::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Set.def()
    }
}

impl Related<super::video::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Video.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
