name: publish

on:
  workflow_dispatch:
    inputs:
      fav:
        description: "publish fav"
        type: boolean
        default: false

env:
  CARGO_TERM_COLOR: always

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: install cargo components
        run: rustup component add clippy

      - name: login to crates.io
        run: cargo login ${{ secrets.CRATESIO }}

      - name: publish fav
        if: ${{ inputs.fav }}
        run: .github/scripts/publish_test.sh fav && .github/scripts/publish.sh fav
